import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./_components/Header";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Headerwrapper } from "./_components/Headerwrapper";
import { CartProvider } from "@/context/cart-context";
import { Header1 } from "./_components/Header1";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CartProvider>
          <Header1 />

          <SidebarProvider>{children}</SidebarProvider>
        </CartProvider>
      </body>
    </html>
  );
}
